[package]
name = "termiGraphics"
version = "0.1.0"
authors = ["guy <guy123levinger@gmail.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
